FROM amazonlinux:2.0.20210617.0
RUN yum groupinstall -y "Development Tools"
RUN yum install -y zlib-devel boost-devel
COPY /source /source
RUN cd source && make clean && make all96  STATIC=1 SSE2=1 &&  make clean && make all384  STATIC=1 SSE2=1
